package com.gtnewhorizons.postea.utility;

import java.util.List;
import java.util.function.BiFunction;
import java.util.function.Function;

import javax.annotation.Nullable;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.world.World;

import org.apache.commons.lang3.tuple.Pair;

import com.google.common.collect.LinkedListMultimap;
import com.gtnewhorizons.postea.api.IDExtenderCompat;

import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
import it.unimi.dsi.fastutil.ints.IntOpenHashSet;

/**
 * A registry for all transformer functions
 */
public class TransformerRegistry {

    private static final LinkedListMultimap<String, BiFunction<String, NBTTagCompound, Boolean>> ITEM_REPLACEMENT_MAP = LinkedListMultimap
        .create();
    public static final LinkedListMultimap<String, Function<BlockConversionInfo, Boolean>> BLOCK_REPLACEMENT_MAP = LinkedListMultimap
        .create();

    /**
     * Map of itemID -> originalName+transformationHandler.
     * Pivoting on the id is faster than pivoting on the strings so this should help with perf a bit.
     * Generated during the mapping update event whilst entering/loading a world.
     */
    private static final Int2ObjectOpenHashMap<Pair<String, List<BiFunction<String, NBTTagCompound, Boolean>>>> RUNTIME_ITEM_REPLACEMENT_MAP = new Int2ObjectOpenHashMap<>();
    /**
     * Map of blockIO -> originalName+transformationHandler.
     * Pivoting on the id is faster than pivoting on the strings so this should help with perf a bit.
     * Generated during the mapping update event whilst entering/loading a world.
     */
    private static final Int2ObjectOpenHashMap<Pair<String, List<Function<BlockConversionInfo, Boolean>>>> RUNTIME_BLOCK_REPLACEMENT_MAP = new Int2ObjectOpenHashMap<>();
    /**
     * List of ids used by dummy items and blocks generated by Postea.
     * Generated during the mapping update event whilst entering/loading a world.
     */
    public static final IntOpenHashSet DUMMY_IDS = new IntOpenHashSet();

    /**
     * Registers a block transformation handler function for the given id.
     *
     * @implNote It doesn't matter if the id doesn't belong to an existing block, a dummy block will be created when
     *           Postea detects that the id isn't associated to a block during the FMLLoadCompleted event. Dependent
     *           mods don't need to worry about this as the block name in the BlockConversionInfo is automatically
     *           updated to the original id when attempting to transform a dummy block. When Postea runs a
     *           transformation on a dummy block and no handler return true, Postea will automatically convert it to
     *           air.
     *
     * @param originalId  The namespaced id of the block to transform.
     * @param transformer The transformation handler that will execute a transformation on the block.
     */
    public static void addBlockReplacement(String originalId, Function<BlockConversionInfo, Boolean> transformer) {
        MissingMappingHandler.createDummyBlockIfNeeded(originalId);
        BLOCK_REPLACEMENT_MAP.put(originalId, transformer);
    }

    /**
     * Registers an item transformation handler function for the given id.
     *
     * @implNote It doesn't matter if the id doesn't belong to an existing item, a dummy item will be created when
     *           Postea detects that the id isn't associated to an item during the FMLLoadCompleted event. Dependent
     *           mods don't need to worry about this as transformation handlers are given the original id associated
     *           with the nbt they are provided when the handler is executed. When Postea runs a transformation on a
     *           dummy item and no handler returns true, Postea will automatically invalidate the stack by removing
     *           its id and idExt fields.
     *
     * @param originalId  The namespaced id of the block to transform.
     * @param transformer The transformation handler that will execute a transformation on the block.
     */
    public static void addItemReplacement(String originalId, BiFunction<String, NBTTagCompound, Boolean> transformer) {
        MissingMappingHandler.createDummyItemIfNeeded(originalId);
        ITEM_REPLACEMENT_MAP.put(originalId, transformer);
    }

    // region FML Life Cycle handlers
    public static void onIdMappingsChanged() {
        DUMMY_IDS.clear();
        RUNTIME_BLOCK_REPLACEMENT_MAP.clear();
        RUNTIME_ITEM_REPLACEMENT_MAP.clear();
        // create a lookup for source block ids.
        for (String key : BLOCK_REPLACEMENT_MAP.keys()) {
            String name = MissingMappingHandler.getDummyIdIfMissing(key);
            if (Block.blockRegistry.getObject(name) instanceof Block block) {
                int id = Block.getIdFromBlock(block);
                RUNTIME_BLOCK_REPLACEMENT_MAP.put(id, Pair.of(key, BLOCK_REPLACEMENT_MAP.get(key)));
                // not using .equals() on purpose, I'm looking for instance, not content equality
                if (key != name) DUMMY_IDS.add(id);
            }
        }
        // create a lookup for source block ids.
        for (String key : ITEM_REPLACEMENT_MAP.keys()) {
            String name = MissingMappingHandler.getDummyIdIfMissing(key);
            if (Item.itemRegistry.getObject(name) instanceof Item item) {
                int id = Item.getIdFromItem(item);
                RUNTIME_ITEM_REPLACEMENT_MAP.put(id, Pair.of(key, ITEM_REPLACEMENT_MAP.get(key)));
                // not using .equals() on purpose, I'm looking for instance, not content equality
                if (key != name) DUMMY_IDS.add(id);
            }
        }
    }

    public static void onServerStopping() {
        RUNTIME_BLOCK_REPLACEMENT_MAP.clear();
        RUNTIME_ITEM_REPLACEMENT_MAP.clear();
        DUMMY_IDS.clear();
    }
    // endregion FML Life Cycle handlers

    // region transformation handlers
    public static boolean isDummyId(int id) {
        return TransformerRegistry.DUMMY_IDS.contains(id);
    }

    public static @Nullable BlockConversionInfo getBlockReplacement(int blockId, byte metadata, World world, int x,
        int y, int z) {
        Pair<String, List<Function<BlockConversionInfo, Boolean>>> data = RUNTIME_BLOCK_REPLACEMENT_MAP.get(blockId);
        if (data == null) return null;
        BlockConversionInfo blockConversionInfo = new BlockConversionInfo(
            // transparently maps the id to the original id if it's a dummy id
            data.getKey(),
            blockId,
            metadata,
            x,
            y,
            z,
            world);
        for (Function<BlockConversionInfo, Boolean> transformer : data.getValue()) {
            if (transformer.apply(blockConversionInfo)) {
                // Not sure if we want to keep this around since this would affect perf a bit, good for debugging
                // though.
                // if (DUMMY_IDS.contains(result.blockID)) FMLLog.warning("returned a success on a non-transformed
                // block!");
                return blockConversionInfo;
            }
        }
        // if we're transforming a dummy block from a missing mapping and it wasn't handled, delete the block.
        if (TransformerRegistry.isDummyId(blockId)) {
            blockConversionInfo.blockID = 0;
            blockConversionInfo.metadata = 0;
            return blockConversionInfo;
        }
        return null;
    }

    public static void transformItem(NBTTagCompound tag) {
        // abort early if tag is bad.
        if (tag.hasNoTags() || !tag.hasKey("id")) return;
        // get handler
        int id = IDExtenderCompat.getItemStackID(tag);
        Pair<String, List<BiFunction<String, NBTTagCompound, Boolean>>> data = RUNTIME_ITEM_REPLACEMENT_MAP.get(id);
        // abort early if handler not found
        if (data == null || data.getValue()
            .isEmpty()) return;

        // apply handlers
        for (BiFunction<String, NBTTagCompound, Boolean> transformer : data.getValue()) {
            if (transformer.apply(data.getKey(), tag)) {
                // Not sure if we want to keep this around since this would affect perf a bit, good for debugging
                // though.
                // if (DUMMY_IDS.contains(IDExtenderCompat.getItemStackID(tag))) FMLLog.warning("returned a success on a
                // non-transformed block!");
                return;
            }
        }
        // if no handler overwrote anything on this stack, and it's a dummy, delete the stack.
        if (TransformerRegistry.isDummyId(id)) {
            tag.removeTag("id");
            tag.removeTag("idExt");
        }
    }
    // endregion transformation handlers
}
